accounts/urls.py
from django.urls import path
import django.contrib.auth.views as auth_views

from .views import ProfileView
from .forms import PwdChangeForm


app_name = "accounts"

urlpatterns = [
    path(
        "login",
        auth_views.LoginView.as_view(
            template_name="accounts/login.html", redirect_authenticated_user=True
        ),
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("", ProfileView.as_view(), name="profile"),
    path(
        "change-password",
        auth_views.PasswordChangeView.as_view(
            template_name="accounts/change_password.html",
            form_class=PwdChangeForm,
            success_url="password-changed",
        ),
        name="change_password",
    ),
    path(
        "password-changed",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="accounts/password_changed.html"
        ),
        name="password_change_done",
    ),
]

clinic_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("account/", include("accounts.urls")),
    path("patient/", include("patients.urls"))
]

main/urls.py
from django.urls import path

from . import views


app_name = "main"

urlpatterns = [
    path(
        "",
        views.MainView.as_view(),
        name="main"
    ),
    path(
        "schedule/search",
        views.ScheduleSearchView.as_view(),
        name="schedule"
    ),
    path(
        "schedule/search-results",
        views.ScheduleListView.as_view(),
        name="search_results"
    ),
    path(
        "appointment/confirm",
        views.AppointmentConfirmView.as_view(),
        name="confirm_appointment"
    ),
    path(
        "appointment/<int:pk>",
        views.AppointmentView.as_view(),
        name="appointment"
    ),
    path(
        "appointment/delete/<int:pk>",
        views.AppointmentDeleteView.as_view(),
        name="delete_appointment"
    )
]

accounts/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordChangeForm


class ProfileForm(forms.ModelForm):
    """
    Represent uneditable user profile data.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["username"].disabled = True
        self.fields["first_name"].disabled = True
        self.fields["last_name"].disabled = True
        self.fields["email"].disabled = True

    class Meta:
        model = User
        fields = ["username", "first_name", "last_name", "email"]


class PwdChangeForm(PasswordChangeForm):
    """
    Change currently logged in user password.
    """
        
    new_password2 = forms.CharField(
        label=("Confirm new password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "new-password"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.label_suffix = ""

accounts/views.py
from django.shortcuts import render
from django.views import View
from django.contrib.auth.mixins import LoginRequiredMixin

from .forms import ProfileForm


class ProfileView(LoginRequiredMixin, View):
    """
    Display currently logged in user details.
    """

    def get(self, request):
        """
        Display currently logged in user details. 
        """

        context = {
            "form": ProfileForm(instance=request.user, label_suffix="")
        }
        return render(request, "accounts/profile.html", context)

accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Change password
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}

<section class="content">
    <div class="column-container align-items-center form-container">
        <h1 class="form-heading">Change password</h1>
        <form action="" method="POST" class="generic-form width-75">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            {% endfor %}
            <button type="submit" class="btn-green width-50 align-center">Submit</button>
        </form>
    </div>
</section>

{% endblock %}

accounts/templates/accounts/login.html
{% extends "base.html" %}
{% load static %}

{% block title %}
    Login
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
<section class="content">
    <div class="column-container align-items-center form-container">
        <h1 class="form-heading">Sign in</h1>
        <form action="" method="POST" class="generic-form width-75">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            {% endfor %}
            <button type="submit" class="btn-green width-50 align-center">Sign in</button>
        </form>
    </div>
</section>

{% endblock %}

accounts/templates/accounts/password_changed.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Password changed!
{% endblock %}

{% block style %}
{% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}

<section class="content">
    <h2 class="section-heading">Password changed successfully</h2>
</section>

{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
    Profile
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
{% include 'includes/navbar.html' %}

<section class="content">
    <h2 class="section-heading">Personal</h2>
    <hr class="section-separator">
    <form action="" class="narrow-form">
        {% for field in form %}
        <div class="narrow-row">
            {{ field.label_tag }}
            {{ field }}
        </div>
        {% endfor %}
        <div class="narrow-row">
            <label>Password</label>
            <a href="{% url 'accounts:change_password' %}" class="btn-green">Change password</a>
        </div>
    </form>
</section>

{% endblock %}