accounts/urls.py
from django.urls import path
import django.contrib.auth.views as auth_views

from .views import ProfileView
from .forms import PwdChangeForm


app_name = "accounts"

urlpatterns = [
    path(
        "login",
        auth_views.LoginView.as_view(
            template_name="accounts/login.html", redirect_authenticated_user=True
        ),
    ),
    path("logout", auth_views.LogoutView.as_view(), name="logout"),
    path("", ProfileView.as_view(), name="profile"),
    path(
        "change-password",
        auth_views.PasswordChangeView.as_view(
            template_name="accounts/change_password.html",
            form_class=PwdChangeForm,
            success_url="password-changed",
        ),
        name="change_password",
    ),
    path(
        "password-changed",
        auth_views.PasswordChangeDoneView.as_view(
            template_name="accounts/password_changed.html"
        ),
        name="password_change_done",
    ),
]

clinic_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("account/", include("accounts.urls")),
    path("patient/", include("patients.urls"))
]

main/urls.py
from django.urls import path

from . import views


app_name = "main"

urlpatterns = [
    path(
        "",
        views.MainView.as_view(),
        name="main"
    ),
    path(
        "schedule/search",
        views.ScheduleSearchView.as_view(),
        name="schedule"
    ),
    path(
        "schedule/search-results",
        views.ScheduleListView.as_view(),
        name="search_results"
    ),
    path(
        "appointment/confirm",
        views.AppointmentConfirmView.as_view(),
        name="confirm_appointment"
    ),
    path(
        "appointment/<int:pk>",
        views.AppointmentView.as_view(),
        name="appointment"
    ),
    path(
        "appointment/delete/<int:pk>",
        views.AppointmentDeleteView.as_view(),
        name="delete_appointment"
    )
]

patients/urls.py
from django.urls import path

from .views import (
    RegistrationView, SuccessRegistrationView, PatientView, SearchResultsView)

app_name = "patients"

urlpatterns = [
    path("register", RegistrationView.as_view(), name="register"),
    path("registered", SuccessRegistrationView.as_view(), name="registered"),
    path("<int:pk>", PatientView.as_view(), name="patient"),
    path("search-results", SearchResultsView.as_view(), name="search_results")
]

templates/includes/navbar.html
<section class="navigation">
    <nav class="navbar">
        <div class="nav-container">
            <a href="{% url 'main:main' %}" class="nav-link">Main</a>
            {% if is_nurse %}
            <a href="{% url 'main:schedule' %}" class="nav-link">Schedule</a>
            <a href="{% url 'patients:register' %}" class="nav-link">Register</a>
            {% endif %}
        </div>
        <div class="search-container">
            <form action="{% url 'patients:search_results' %}" method="GET">
                <input type="text" class="search" name="query" placeholder="Search...">
                <button type="submit" class="search-button"><i class="fa-solid fa-magnifying-glass nav-link"></i></button>
            </form>
        </div>
        <div class="account-container">
            <a href="{% url 'accounts:profile' %}" class="nav-link">
                <i class="fa-regular fa-user"></i>
            </a>
            <a href="{% url 'accounts:logout' %}" class="nav-link logout">
                <i class="fa-solid fa-arrow-right-from-bracket"></i>
            </a>
        </div>
    </nav>
    <hr class="nav-separator">
</section>