clinic_management_system/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("main.urls")),
    path("account/", include("accounts.urls")),
    path("patient/", include("patients.urls"))
]

main/urls.py
from django.urls import path

from . import views


app_name = "main"

urlpatterns = [
    path(
        "",
        views.MainView.as_view(),
        name="main"
    ),
    path(
        "schedule/search",
        views.ScheduleSearchView.as_view(),
        name="schedule"
    ),
    path(
        "schedule/search-results",
        views.ScheduleListView.as_view(),
        name="search_results"
    ),
    path(
        "appointment/confirm",
        views.AppointmentConfirmView.as_view(),
        name="confirm_appointment"
    ),
    path(
        "appointment/<int:pk>",
        views.AppointmentView.as_view(),
        name="appointment"
    ),
    path(
        "appointment/delete/<int:pk>",
        views.AppointmentDeleteView.as_view(),
        name="delete_appointment"
    )
]

main/models.py
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse

from patients.models import Patient
from .validators import is_physician


class Schedule(models.Model):
    """
    Employee shift date, start time and end time.
    """

    date = models.DateField()
    start = models.TimeField()
    end = models.TimeField()
    employee = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("date", "employee"),
                name="unique_employee_work_date",
                violation_error_message="Employee already has a shift"\
                    "scheduled for that day!"
            )
        ]

    def __str__(self):
        return f"{self.emp_full_name()} {self.date}"

    def emp_full_name(self):
        return f"{self.employee.first_name} {self.employee.last_name}"


class Appointment(models.Model):
    """
    Doctor appointments.
    """

    datetime = models.DateTimeField()
    patient = models.ForeignKey(
        Patient,
        on_delete=models.SET_DEFAULT,
        default="PATIENT REMOVED"
    )
    doctor = models.ForeignKey(
        User,
        on_delete=models.SET_DEFAULT,
        default="DOCTOR REMOVED",
        validators=[is_physician]
    )
    purpose = models.CharField(max_length=200, null=False)
    examination = models.TextField(null=True)
    diagnosis = models.CharField(max_length=250, null=True)
    advice = models.TextField(null=True)
    prescription = models.TextField(null=True)
    took_place = models.BooleanField(null=True)

    class Meta:
        constraints = [
            models.UniqueConstraint(
                fields=("datetime", "doctor"),
                name="unique_doctor_appointment",
                violation_error_message="Doctor already has an appointment at"\
                    "this datetime!"
            ),
            models.UniqueConstraint(
                fields=("datetime", "patient"),
                name="unique_patient_appointment",
                violation_error_message="Patient already has an appointment "\
                    "at this datetime!"
            )
        ]

    def clean(self):
        """
        Check if user in doctor field is a physician on schedule.
        """
        employee = User.objects.filter(
            models.Q(groups__name__iexact="physicians"),
            id=self.doctor.id
        )
        schedule = Schedule.objects.filter(
            models.Q(date=self.datetime),
            employee__id=self.doctor.id
        )

        if not employee.exists():
            raise ValidationError("User is not a physician!")
        elif not schedule.exists():
            raise ValidationError("Doctor not on schedule!")

    def __str__(self):
        datetime_string = self.datetime.strftime("%Y-%m-%d %H:%M")
        return f"{datetime_string} {self.doctor} {self.patient}"

    def save(self, *args, **kwargs):
        self.clean()
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("main:appointment", args=[self.id])

main/forms.py
from datetime import date, timedelta

from django import forms
from django.contrib.auth.models import Group, User

from .models import Schedule, Appointment


AVAILABLE_DATES = [date.today() + timedelta(days=i) for i in range(7)]
AVAILABLE_DATES = [(d, d) for d in AVAILABLE_DATES]


class ScheduleModelForm(forms.ModelForm):
    """
    Add an optional date_to field to Schedule model.

    Apply work time to a range of dates when upading schedule from admin page.
    """

    date_to = forms.DateField(
        label="Date to",
        required=False,
        widget=forms.SelectDateWidget
    )

    class Meta:
        model = Schedule
        fields = ("date", "date_to", "start", "end", "employee")


class ScheduleSearchForm(forms.Form):
    """
    Display doctors available for appointments.
    """

    specialties = forms.ModelChoiceField(
        queryset=Group.objects.exclude(name="nurses")
    )
    date = forms.DateField(widget=forms.Select(choices=AVAILABLE_DATES))
    employee = forms.ModelChoiceField(
        queryset=User.objects.none(), required=False
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if "employee" in self.data:
            try:
                emp_id = int(self.data.get("employee"))
                self.fields["employee"].queryset = User.objects.filter(
                    id=emp_id
                )
            except (ValueError, TypeError):
                pass


class AppointmentConfirmForm(forms.Form):
    """
    Get patient personal ID and visit purpose.
    """

    personal_id = forms.CharField(max_length=11)
    purpose = forms.CharField(max_length=200, widget=forms.Textarea)


class AppointmentModelForm(forms.ModelForm):
    """
    View scheduled appointment details.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["doctor"].disabled = True
        self.fields["patient"].disabled = True
        self.fields["prescription"].required = False

    class Meta:
        model = Appointment
        fields = "__all__"
        widgets = {
            "datetime": forms.TextInput(attrs={"readonly": True})
        }

main/views.py
import datetime

from django.db.models import Q
from django.db.utils import IntegrityError
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse
from django.views import View

from .forms import (
    ScheduleSearchForm, AppointmentConfirmForm, AppointmentModelForm
)
from .models import Schedule, Appointment
from .utils import get_day_schedule, get_next_appointment
from patients.models import Patient


class MainView(LoginRequiredMixin, View):
    """
    Display main page.
    """

    def get(self, request):
        """
        Next appointment for doctor. List of scheduled appointments for nurse.
        """

        user = self.request.user
        is_nurse = user.groups.filter(name__iexact="nurses").exists()
        is_doctor = user.groups.filter(name__iexact="physicians").exists()

        if is_doctor:
            appointment = get_next_appointment(user)
            if appointment:
                form = AppointmentModelForm(
                    instance=appointment,
                    label_suffix=""
                )
                context = {
                    "form": form
                }
                return render(request, "main/index.html", context)
        elif is_nurse:
            appointments = Appointment.objects.filter(
                Q(datetime__gte=datetime.datetime.today())
            ).order_by("datetime")
            context = {
                "appointments": appointments
            }
            return render(request, "main/index.html", context)
        return render(request, "main/index.html")

    def post(self, request):
        """
        Update appointment details and display the next one if form is valid.
        Display error messages otherwise.
        """

        doctor = self.request.user
        datetime = self.request.POST.get("datetime")
        appointments = Appointment.objects.filter(
            Q(doctor=doctor)
            & Q(datetime=datetime)
        )

        form = AppointmentModelForm(request.POST, instance=appointments[0])

        if form.is_valid():
            form.save()
            doctor = self.request.user
            next_appointment = get_next_appointment(doctor)
            if next_appointment:
                new_form = AppointmentModelForm(
                    instance=next_appointment,
                    label_suffix=""
                )
                context = {
                    "form": new_form
                }
                return render(request, "main/index.html", context)
            return render(request, "main/index.html")
        context = {
            "form": form
        }
        return render(request, "main/index.html", context)


class ScheduleSearchView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Allow nurses to schedule appointments.
    """

    def test_func(self):
        """
        Allow only nurses
        """
        return self.request.user.groups.filter(name__iexact="nurses").exists()

    def get(self, request):
        """
        Schedule form page or selected specialists for ajax request.
        """

        if request.headers.get("X-Requested-With") == "XMLHttpRequest":
            specialty = request.GET.get("specialty")
            specialists = User.objects.filter(groups__name=specialty)
            context = {"specialists": specialists}
            return render(request, "main/includes/specialists.html", context)

        form = ScheduleSearchForm()
        context = {
            "form": form
        }

        return render(request, "main/schedule.html", context)


class ScheduleListView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Display schedule search results.
    """

    def test_func(self):
        """
        Allow only nurses
        """
        return self.request.user.groups.filter(name__iexact="nurses").exists()

    def get(self, request):
        """
        Get search results or redirect to schedule search form if ivalid values
        provided.
        """

        spec_id = request.GET.get("specialties")
        emp_id = request.GET.get("employee")
        date = request.GET.get("date")
        if spec_id is None or date is None:
            return HttpResponseRedirect(reverse("main:schedule"))
        elif emp_id:
            schedules = Schedule.objects.filter(
                Q(employee__groups__id=spec_id)
                & Q(employee__id=emp_id)
                & Q(date=date)
            )
        else:
            schedules = Schedule.objects.filter(
                Q(employee__groups__id=spec_id)
                & Q(date=date)
            )

        context = {
            "date": datetime.datetime.strptime(date, "%Y-%m-%d"),
            "schedule": get_day_schedule(schedules)
        }
        return render(request, "main/schedule_search_results.html", context)

    def post(self, request):
        """
        Store appointment details in session and redirect to confirmation page.
        """

        request.session["hour"] = request.POST.get("hour")
        request.session["date"] = request.POST.get("date")
        request.session["doctor_id"] = request.POST.get("doctor_id")

        return HttpResponseRedirect(reverse("main:confirm_appointment"))


class AppointmentConfirmView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Select a patient and confirm appointment.
    """

    def test_func(self):
        """
        Allow only nurses
        """
        return self.request.user.groups.filter(name__iexact="nurses").exists()

    def get(self, request):
        """
        Display confirmation form or redirect to schedule form if no valid
        session data found.
        """

        date_string = request.session.get("date")
        time_string = request.session.get("hour")
        doctor_id = request.session.get("doctor_id")
        if (date_string is None
                or time_string is None
                or doctor_id is None):
            return HttpResponseRedirect(reverse("main:schedule"))

        form = AppointmentConfirmForm(label_suffix="")
        context = {
            "form": form
        }
        return render(request, "main/appointment_confirm.html", context)

    def post(self, request):
        """
        Confirm appointment and redirect if valid. Display errors otherwise.
        """

        form = AppointmentConfirmForm(request.POST)
        context = {
            "form": form
        }

        if form.is_valid():
            personal_id = form.cleaned_data["personal_id"]
            try:
                patient = Patient.objects.get(personal_id=personal_id)
            except Patient.DoesNotExist as e:
                context["error"] = "Invalid patient id"
                return render(request, "main/appointment_confirm.html", context)

            date_string = request.session.get("date")
            time_string = request.session.get("hour")
            doctor_id = request.session.get("doctor_id")
            if (date_string is None
                    or time_string is None
                    or doctor_id is None):
                context["error"] = "Fill out schedule form first."
                return render(request, "main/appointment_confirm.html", context)

            try:
                doctor = User.objects.get(pk=doctor_id)
            except User.DoesNotExist as e:
                context["error"] = "Invalid doctor ID"
                return render(request, "main/appointment_confirm.html", context)

            date = datetime.datetime.strptime(date_string, "%Y-%m-%d").date()
            time = datetime.datetime.strptime(time_string, "%H:%M").time()
            appointment_datetime = datetime.datetime.combine(date, time)
            try:
                appointment = Appointment(
                    datetime=appointment_datetime,
                    patient=patient,
                    doctor=doctor,
                    purpose=form.cleaned_data["purpose"]
                )
                appointment.save()
            except IntegrityError as e:
                context["error"] = str(e)
                return render(request, "main/appointment_confirm.html", context)
            request.session["hour"] = None
            request.session["date"] = None
            request.session["doctor_id"] = None
            return HttpResponseRedirect(reverse("main:main"))

        else:
            return render(request, "main/appointment_confirm.html", context)


class AppointmentView(LoginRequiredMixin, View):
    """
    Display a single appointment.
    """

    def get(self, request, pk):
        """
        Display appointment details or 404 if invalid appointment ID.
        """

        appointment = get_object_or_404(Appointment, id=pk)
        form = AppointmentModelForm(instance=appointment)
        context = {
            "form": form
        }
        return render(request, "main/appointment.html", context)

    def post(self, request, pk):
        """
        Update appointment details and display them imidiately on success.
        Display page with errors otherwise.
        """

        appointment = get_object_or_404(Appointment, id=pk)
        form = AppointmentModelForm(request.POST, instance=appointment)

        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse("main:appointment", args=[pk]))

        context = {
            "form": form
        }
        return render(request, "main/appointment.html", context)


class AppointmentDeleteView(LoginRequiredMixin, UserPassesTestMixin, View):
    """
    Confirm and delete appointment.
    """

    def test_func(self):
        """
        Allow only nurses
        """
        return self.request.user.groups.filter(name__iexact="nurses").exists()

    def get(self, request, pk):

main/templates/main/appointment.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
{% include "includes/navbar.html" %}

<section class="content">
    <form action="" method="POST" class="generic-form width-75">
        {% csrf_token %}
        {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
        {% endfor %}
        <div class="row-container">
            <button type="submit" class="btn-green width-50 {% if form.instance.took_place or is_doctor %}align-center {% endif %}">Submit</button>
            {% if not form.instance.took_place and not is_doctor%}
            <a href="{% url 'main:delete_appointment' form.instance.id %}" class="btn-red width-50">Cancel</a>
            {% endif %}
        </div>

    </form>
</section>

{% endblock %}

main/templates/main/appointment_confirm.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Confirm appointment
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
{% include "includes/navbar.html" %}

<section class="content">
    <div class="column-container align-items-center form-container">
        <h1 class="form-heading">Confirm visit</h1>
        <form id="" action="" method="POST" class="generic-form width-75">
            {% csrf_token %}
            {% for field in form %}
                {{ field.label_tag }}
                {{ field }}
                {{ field.errors }}
            {% endfor %}
            <button type="submit" class="btn-green width-50 align-center">Submit</button>
            {% if error %}
            <ul class="errorlist">
                <li>{{ error }}</li>
            </ul>
            {% endif %}
        </form>
    </div>
</section>

{% endblock %}

main/templates/main/appointment_delete.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Login
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
<section class="content">
    <div class="column-container align-items-center form-container">
        <h1 class="form-heading">Cancel appointment</h1>
        <form action="" method="POST" class="generic-form width-75">
            {% csrf_token %}
            <input type="hidden" value="{{ appointment.id }}" name="appointment_pk">
            <p>Are you sure you want to cancel {{ appointment.patient.first_name }} {{ appointment.patient.last_name }}
                {{ appointment.datetime|date:"l, F j, Y" }} appointment with {{ appointment.doctor.first_name }} 
                {{ appointment.doctor.last_name }}? </p>
            <div class="spaced-container">
                <a href="{{ appointment.get_absolute_url }}" class="btn-red width-50">Cancel</a>
                <button type="submit" class="btn-green width-50">Confirm</button>
            </div>
        </form>
    </div>
</section>

{% endblock %}

main/templates/main/index.html
{% extends "base.html" %}
{% load static %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
{% include "includes/navbar.html" %}

<section class="content">
{% if is_doctor %}
    {% if form %}
    <form action="" method="POST" class="generic-form width-75">
        {% csrf_token %}
        {% for field in form %}
        {{ field.label_tag }}
        {{ field }}
        {{ field.errors }}
        {% endfor %}
        <button type="submit" class="btn-green width-50 align-center">Submit</button>
    </form>
    {% else %}
    <h1>No appointments scheduled for today.</h1>
    {% endif %}

{% elif is_nurse %}
    {% for appointment in appointments %}
    <div class="spaced-container">
        <p>{{ appointment.datetime|date:"l, F j, Y H:i" }}
            {{ appointment.doctor.first_name }} {{ appointment.doctor.last_name }}
            {{ appointment.patient.first_name }} {{ appointment.patient.last_name }}</p>
        <a href="{% url 'main:delete_appointment' appointment.id %}" class="btn-red">Cancel</a>
    </div>
    <hr class="section-separator">
    {% endfor %}
{% endif %}

</section>

{% endblock %}

main/templates/main/schedule.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Schedule an appointment
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
{% include "includes/navbar.html" %}

<section class="content">
    <div class="column-container align-items-center form-container">
        <h1 class="form-heading">Schedule</h1>
        <form id="schedule-form" action="{% url 'main:search_results' %}" method="GET" class="generic-form width-75"
            specialties-url="{% url 'main:schedule' %}">
            {% for field in form %}
            {{ field.label_tag }}
            {{ field }}
            {{ field.errors }}
            {% endfor %}
            <button type="submit" class="btn-green width-50 align-center">Submit</button>
        </form>
    </div>
</section>
<script src="{% static 'main/main.js' %}"></script>

{% endblock %}

main/templates/main/schedule_search_results.html
{% extends "base.html" %}
{% load static %}

{% block title %}
Schedule an appointment
{% endblock %}

{% block style %}
<link rel="stylesheet" href="{% static 'forms.css' %}">
{% endblock %}

{% block content %}
{% include "includes/navbar.html" %}

<section class="content">
    <h1>{{ date|date:"l, F j, Y" }}</h1>
    {% for appointment in schedule %}
        <div class="spaced-container">
            <div>{{ appointment.hour|time:"H:i" }} {{ appointment.employee_full_name }}</div>
            <form action="" method="POST">
                {% csrf_token %}
                <input type="hidden" value='{{ appointment.hour|time:"H:i" }}' name="hour">
                <input type="hidden" value='{{ date|date:"Y-m-d" }}' name="date">
                <input type="hidden" value="{{ appointment.employee_id }}" name="doctor_id">
                <button type="submit" class="btn-green">Schedule</button>
            </form>
        </div>
        <hr class="section-separator">
    {% endfor %}
</section>
{% endblock %}